//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TruckingCar.data.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rentals
    {
        public int RentID { get; set; }
        public int OrderID { get; set; }
        public System.DateTime StartTime { get; set; }
        public System.DateTime EndTime { get; set; }
        public decimal Price { get; set; }
    
        public virtual Orders Orders { get; set; }
    }
}
